### ISSUE TITLE
roadmap for corrections and improvements

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#55]
List of to's do after assessing the results of the survey 

Stefania: 

- [x] adjust table content assignment newspapers 
- [x] adjust assignments Archival to Digital, to format Boder (change place for instruction, reading and viewing suggestions 
- [x] include thumbnail of clip in intro assignment (example Muybridge)
- [x] correct data in page Defining - Literature (dates and spaces) 
- [ ] create PDF from google doc and upload in GitHub 
- [x] add links to appropriate clips and literature  to What this platform is about
- [x] change place of Objectives in What the platform is about 
- [x] change animations to most recent version (Boder, Ranke, Transformation are ready) 
- [x] check whether have to redo quiz again with Shahed 
- [x] think of snappier titles for Assignments 
- [x] add definition DSC in Definition page 
- [x] add content to page Skill Training, and Expert Meeting, show page: under construction 
- [x] check mentioning of typos, 

after review with Andreas and Gerben 5-9-2018
- [x] with Home Page: turn: ‘Definition’  into  ‘What is Digital Source Criticism?’
- [x] First : What is DSC about?  First ‘Why’ and then ‘Objectives’
- [x] Offer example of scenarios in page Structure of the Lessons
- [x] explain about the mix of digital 
 
Daniele:
- [x] make 3 slides for Wednesday: Design Policy - Reflects concept of SDC: colours, glitch, simple structure, if necessary explanation in section of ABOUT 
- [x] think of solution for time indication  for assignment (10 min) is ugly!!!
- [x] add SMALL at the right side below the INTRO for animation, in another form then ordinary text
- [x] add SMALL at the right side below intro for quiz, in another form then ordinary text (symbol, colour)
- [x] Add Title - ASSIGNMENTS   on top of assignments 
- [x] Add MEDIUM besides ASSIGNMENTS 
- [x] Created Page for LARGE , with title: under construction, or people will think it has been lost, as it is marked in the introduction and structure of the platform, but it cannot be found anywhere 
- [x] take link away that open assignment in wide screen 
- [x] take T-shirts away and replace them with other symbol for small, medium, Large 
- [x] add SMALL/ANIMATION/QUIZ  max 15 min
- [x] add MEDIUM/one or more assignments. max 60 min
- [x] add LARGE/ engage with a workshop.  1 day

after review 5-9-2018
- [x]  Home page; amount of metadata at the bottom of images that are shown is inconsistent - complement 
- [x]  rephrase 1 fixed part for the moving text and one dynamic - 
**Ranke.2 is a Teaching Platform** 
-- on Digital Source Criticism 
-- on how to critically assess historical digital sources
-- on different types of data 
-- on how analogue sources are turned into digital representations 
- [x]   Glitch philosophy is not reflected in other pages than HOME: coloured background or cyan line 
- [ ]  create Moodle import: how? Discuss with Shahed, plan meeting
- [ ]  DG add possibility for feedback from audience
- [ ] if you are looking for XL, contact our developer, add L for Boder

**Comment by danieleguido** [comment]
hi @stefaniascagliola I've updated the issue, we now have ticks ;)
