### ISSUE TITLE
new roadmap with last issues before launch on 25th Daniele and Fred 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#79]
- [ ] problems with uploading PDFs 

1. I have created slugs  tutorial-tiki    struggling-timeline and placed them here: 
https://docs.google.com/spreadsheets/d/1kRGo8pfsXjugWRRM3H5T2Ew-sHtGiqDPH0grV74y5MA/edit#gid=555142302 

2. then I have uploaded the pdfs in Assets:
struggling-timeline.pdf
tutorial-tiki.pdf 

3. then I have added the pdf in the list of documents: in the assignment metadata 

documents:
  - tutorial-tiki
  - struggling-timeline
---
4. then I have added them reference in the content like this:

- If you need more guidance, then follow the step by step instructions provided in [ref](tutorial-tiki) 

- For assessing the pros and cons of different tools for creating timelines, consult this guide [ref](struggling-timeline)

5. Then I have asked Fred to run the script - but they don't show, why???? 

- [x] wait for proof read version of  Sander trace date online publication pdf, and of newspapers interface explanation pdf, and then process for upload. STEFANIA

- [x] add links to appropriate clips and literature  to What this platform is about - I have added the ref to articles that cover the topics mentioned in the texts blocs (from analogue to digital, hybrid historian), but I only want to show (Hjorland, 2008) and not the long line of text, how to fix?  DANIELE 

- [ ] change animations to most recent version STEFANIA
- [x] Boder - DONE
- [x] Boder French and German subtitels - to be delivered  CRISTINA
- [x] RANKE - to be delivered CRISTINA - in GERMAN and ENGLISH 
- [ ] TRANSFORMATION - to be delivered CRISTINA - with French and German subtitles 
- [ ] check whether have to redo quiz again with Shahed  STEFANIA 
- [ ] wait for last version clip Ranke (Cristina) and Transformation (Alexandre) and then insert quiz English, French, German in Playposit - STEFANIA 

- [x] add content to page Skill Training, and Expert Meeting, show page: under construction STEFANIA 
- [ ] check mentioning of typos, survey STEFANIA 

- [ ] Add Title - ASSIGNMENTS   on top of assignments DANIELE 
- [x] Check changes metadata clips HOME PAGE DANIELE
- [x] Check content and structure WHO WE ARE  DANIELE 
- [x] Create CONTACT possibility - e-mail address DANIELE 

- [ ] Short description of what will come in Page for LARGE , STEFANIA
- [x] Short description somewhere about who Ranke was (cut passage from clip Cristina and show somewhere else?) STEFANIA DANIELE  
- [ ]  create Moodle import: how? Discuss with Shahed  DANIELE 

- [ ]  check missing sentences in translations with Sarah and Maria Cristina - STEFANIA
- [x]  work on answer template Boder and Ranke - FRED STEFANIA

- [x] Insert English proofread corrections assignments RANKE  1 to 3 - STEFANIA
- [x] Insert English proofread corrections assignments RANKE  4 to 7 - STEFANIA
- [ ] insert French and German translations assignments RANKE 1 to 7 #87  - FRED 

- [ ] last check up Website  with translators Tuesday 23-10 - STEFANIA
